title: Shaw
description: Goodbye.
google_analytics: G-78DTRCTD35
theme: jekyll-theme-cayman
show_urls: true
github:
  root_url: https://www.imdb.com/title/tt1839578/characters/nm0009918
  shaw_url: https://www.imdb.com/title/tt1839578/characters/nm1083404
  description: I figured I should say goodbye<br>Sorry, Root<br>This... just isn't my thing